### ISSUE TITLE
New user's new fish should save to database on creation

### ISSUE THREAD

**Issue by kiglaze** [vaijiNeel/BigFishSmallFish#12]
When someone gets to the popup window that asks if the user already has a fish, and the user clicks "No", then clicks the screen to add their new fish, the data for that fish marker should get saved to the database so everyone (including on other computers) can see it. Variables will store information for which fish is the current user's fish. This information on the current user's fish will also be saved to local storage (see another task for why).

**Comment by devonwood35** [comment]
feature/login

**Comment by devonwood35** [comment]
Done
