### ISSUE TITLE
Add our BigFishSmallFish repository to an organization

### ISSUE THREAD

**Issue by kiglaze** [vaijiNeel/BigFishSmallFish#17]
Add our BigFishSmallFish repository to an organization (as long as you know for sure it won't delete our repository)!!! One thing you could try if that is not possible is to create a brand new repository that is associated with an organization, then copy over our current repository to that new one. Then you could share your findings on how to do this. Also please let us know if we have to switch over to a new repository.

**Comment by vaijiNeel** [comment]
Deferred
