### ISSUE TITLE
Create function that can re-center map

### ISSUE THREAD

**Issue by kiglaze** [vaijiNeel/BigFishSmallFish#19]
Create a function that re-centers the map based upon two input parameters: latitude and longitude.
This will require use of the google api. Right now, you will see that a map center point is set (and hard-coded) for when the map initially gets set up. However, we want a function that will re-center the map using the function's parameters (we should be able to call that function at different places in the code, NOT just when the map first loads).

**Comment by vaijiNeel** [comment]
code complete and merged to master
